version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - product-service
      - order-service
      - payments-service

  user-service:
    build: ./user-service
    ports:
      - "5001:5001"

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"

  payments-service:
    build: ./payments-service
    ports:
      - "5004:5004"